#!/bin/bash
#
#
# (c) by Daniel Scheidler      Aug 2015

versionValue=$(<version.txt)
echo "Old Version: " $versionValue

IFS='.' read -a array <<< "$versionValue"
newVersion=''
for index in "${!array[@]}"
do
  if [ $index -eq 2 ]; then
    tmp=.$((${array[index]}+1));
  elif [ $index -eq 0 ]; then
    tmp=${array[index]};
  else
    tmp=.${array[index]};
  fi
  newVersion=$newVersion$tmp;
done

echo $newVersion > version.txt
echo "New Version: " $newVersion


git add classes
git add includes
git add *.php
git add functions
git add *.sh
git add *.sql
git add commitUpdate
git add *.txt

#-----------------------------------------------------------------
if [ -f versionHistory.tmp ];
then
  rm versionHistory.tmp
fi

echo  "Geben Sie die Anpassungen des Commits an: "
echo  "Beenden Sie die Eingabe mit 2x Enter (also einer Leerzeile)"
while read changes 
do
   if  [ ${#changes} -gt 0 ]; then
      echo "$changes"        >> versionHistory.tmp
   else
      break
   fi
done

echo ""                      >> versionHistory.txt
echo "Version: $newVersion"  >> versionHistory.txt
echo "---------------------" >> versionHistory.txt
echo ""                      >> versionHistory.txt
cat versionHistory.tmp       >> versionHistory.txt
#-----------------------------------------------------------------


git commit --file versionHistory.tmp
git push

